### ISSUE TITLE
could you try to read pretrained model

### ISSUE THREAD

**Issue by emedinac** [gengyanlei/segmentation_pytorch#4]
Hi, I implemented a pytorch version for deeplabv3+ (it is unorganized still). I only achieved 65% in PASCAL2012 using the augmented PASCAL in the training phase. This happened due to I didn't use the complete Xception-like backbone. I think you should try to read the backbone (or maybe the complete network in order to compare the models) from the TF model before training. This GitHub describes a code to read the model from TF for Keras.

https://github.com/bonlime/keras-deeplab-v3-plus/blob/master/extract_weights.py

**Comment by gengyanlei** [comment]
@edgarmedina1801 
Chinese：您好，在这里说明一下：由于pytorch有已经在ImageNet上面训练好的resnets，因此我没有完全按照deeplab_v3_plus论文中的结构搭建。直接使用pytorch的torchvision里面的models作为预训练模型。
English：Hello, here to explain: Because pytorch has resnets already trained on ImageNet, I did not completely follow the structure in the deeplab_v3_plus paper. Directly use the models in the torpechch's torchvision as a pre-training model.

**Comment by gengyanlei** [comment]
@edgarmedina1801 
Chinese：另外，我在readme中也注释了我的修改。
